- m2cgen/ast.py
- m2cgen/examples.py
- m2cgen/interpreters/java.py
Example code, verified in JVM runtime:
```java
public class Model {
public static double score(double[] input) {
double var0;
double var1;
if ((1) == (1)) {
var1 = 1;
} else {
var1 = 2;
}
if ((var1 + 2) >= (1 / 2)) {
var0 = 1;
} else {
var0 = 2;
}
return var0;
}
}
```
> Implement java if statements

- m2cgen/ast/interpreters/code_generator.py
- m2cgen/ast/interpreters/python/code_generator.py
- m2cgen/ast/interpreters/python/interpreter.py
- m2cgen/examples.py
- m2cgen/exporters/__init__.py
- m2cgen/exporters/python.py
Example: https://gist.github.com/krinart/aa9c8b9e56e084982593282389942e09
> Add python support

- m2cgen/assemblers/__init__.py
- m2cgen/assemblers/svm.py
- m2cgen/assemblers/utils.py
- m2cgen/ast.py
- m2cgen/interpreters/c/interpreter.py
- m2cgen/interpreters/go/interpreter.py
- m2cgen/interpreters/interpreter.py
- m2cgen/interpreters/java/interpreter.py
- m2cgen/interpreters/python/interpreter.py
- tests/assemblers/test_svm.py
- tests/e2e/executors/c.py
- tests/e2e/test_e2e.py
- tests/interpreters/test_c.py
- tests/interpreters/test_go.py
- tests/interpreters/test_java.py
- tests/interpreters/test_python.py
- tests/utils.py
Please note that the multi-class support as well as generated examples will be added in a subsequent PR.
>  Initial implementation of the SVM model assembler

- .gitignore
Refer to https://github.com/github/gitignore/blob/master/Python.gitignore.
> enhance gitignore file

- .travis.yml
Refer to https://github.com/BayesWitnesses/m2cgen/pull/125#issuecomment-563389527.
> control Travis workflow by env variables and do not store commands in them

- requirements-test.txt
Simply bump versions of testing-related tools to the latest ones.
> fix CI tests

- tests/assemblers/test_lightgbm.py
In #130 only e2e test was added.
> added API test for LightGBM rf mode to increase code coverage

- m2cgen/assemblers/boosting.py
Refer to https://github.com/BayesWitnesses/m2cgen/pull/139#discussion_r365435868.
> define leaves_cutoff_threshold as constant

- .travis.yml
- .travis/setup.sh
- Dockerfile
- README.md
- m2cgen/__init__.py
- m2cgen/cli.py
- m2cgen/exporters.py
- m2cgen/interpreters/__init__.py
- m2cgen/interpreters/php/code_generator.py
- m2cgen/interpreters/php/interpreter.py
- m2cgen/interpreters/php/linear_algebra.php
- m2cgen/interpreters/powershell/code_generator.py
- tests/e2e/executors/__init__.py
- tests/e2e/executors/php.py
- tests/e2e/test_e2e.py
- tests/interpreters/test_php.py
- tools/generate_code_examples.py
PHP is one of the most popular programming language for web development. So, use cases are quite obvious - online model serving.
> added PHP code generator

- README.md
- m2cgen/assemblers/__init__.py
- m2cgen/assemblers/base.py
- m2cgen/assemblers/boosting.py
- requirements-test.txt
- tests/assemblers/test_xgboost.py
- tests/e2e/test_e2e.py
The follow-up PR to https://github.com/BayesWitnesses/m2cgen/pull/133. The `class_idx` argument looks pretty ugly in the `_assemble_single_output`, but so far I couldn't come up with a better name.
> XGBoost linear model support 

- m2cgen/assemblers/__init__.py
- tests/e2e/test_e2e.py
This will allow to avoid cases like in #160 and #131,
> sort estimators in e2e tests and in __init__ alphabetically

- m2cgen/assemblers/boosting.py
Related to `LEAVES_CUTOFF_THRESHOLD` logic was removed in #158.
> removed unused code

- tests/assemblers/test_svm.py
Deduplicate code in test according to the https://github.com/BayesWitnesses/m2cgen/pull/176#discussion_r392713761.
> slight test refactoring

- m2cgen/assemblers/boosting.py
- requirements-test.txt
- tests/assemblers/test_xgboost.py
Fixed #183.
Refer to 
https://github.com/dmlc/xgboost/blob/cfae247231e4977a78b255810565369c934fe1b5/tests/python/test_with_sklearn.py#L535-L537
> update code for XGBoost to support newer versions

- m2cgen/assemblers/boosting.py
- m2cgen/assemblers/ensemble.py
- m2cgen/assemblers/linear.py
- m2cgen/assemblers/svm.py
- m2cgen/assemblers/utils.py
- m2cgen/interpreters/code_generator.py
List comprehensions are known to be faster than loops with `append`, so use them where possible.
Some other minor speedups.
> slight speedup for code generation

- m2cgen/assemblers/svm.py
I believe Issues is a better place for `FIXME` and `TODO` things 🙂 .
Just created #202.
> remove TODO comment

- README.md
Although we do not have E2E test for VBA (and I don't think that it is technically possible), I manually check all VB changes in Excel.
Refer to https://github.com/BayesWitnesses/m2cgen/blob/813d2e99638fe3116e36802b7119f13629af9dbf/m2cgen/exporters.py#L135-L137
> mention in README that VB code is VBA-compatible

- .ci/test.sh
- .github/workflows/main.yml
- Dockerfile
- README.md
- codecov.yml
- requirements-test.txt
Refer to https://github.com/BayesWitnesses/m2cgen/pull/358#issuecomment-812651179 and https://github.com/lemurheavy/coveralls-public/issues/1149#issuecomment-812927959.
> Migrate from coveralls to codecov

- Dockerfile
Always install the latest available version of R.
> Bump R version in Docker

- m2cgen/assemblers/boosting.py
- m2cgen/assemblers/linear.py
- tests/assemblers/test_lightgbm.py
- tests/assemblers/test_linear.py
- tests/assemblers/test_xgboost.py
> Use SigmoidExpr in the codebase

- tests/e2e/test_e2e.py
> Add support for extremely randomized trees in LightGBM

- .github/workflows/main.yml
- Dockerfile
- README.md
- m2cgen/__init__.py
- m2cgen/cli.py
- m2cgen/exporters.py
- m2cgen/interpreters/__init__.py
- m2cgen/interpreters/powershell/code_generator.py
- m2cgen/interpreters/rust/code_generator.py
- m2cgen/interpreters/rust/interpreter.py
- m2cgen/interpreters/rust/linear_algebra.rs
- m2cgen/interpreters/rust/sigmoid.rs
- m2cgen/interpreters/rust/softmax.rs
- tests/e2e/executors/__init__.py
- tests/e2e/executors/rust.py
- tests/e2e/test_e2e.py
- tests/interpreters/test_rust.py
> Add Rust code generator

- README.md
- m2cgen/assemblers/__init__.py
- m2cgen/assemblers/svm.py
- tests/e2e/test_e2e.py
- tests/utils.py
> Add support for OneClassSVM

- m2cgen/interpreters/javascript/code_generator.py
- tests/interpreters/test_javascript.py
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality
> Use strict equality in JavaScript

- tests/test_ast.py
> Add test for `count_exprs()` with unknown expr

- m2cgen/interpreters/powershell/code_generator.py
- tests/interpreters/test_c.py
- tests/interpreters/test_c_sharp.py
- tests/interpreters/test_dart.py
- tests/interpreters/test_f_sharp.py
- tests/interpreters/test_go.py
- tests/interpreters/test_haskell.py
- tests/interpreters/test_java.py
- tests/interpreters/test_javascript.py
- tests/interpreters/test_php.py
- tests/interpreters/test_powershell.py
- tests/interpreters/test_python.py
- tests/interpreters/test_r.py
- tests/interpreters/test_ruby.py
- tests/interpreters/test_rust.py
- tests/interpreters/test_visual_basic.py
> Test not equal operator in interpreters tests

- tests/test_fallback_expressions.py
> Add test for expressions without fallback implementations

- generated_code_examples/javascript/classification/lightgbm.js
- generated_code_examples/javascript/classification/random_forest.js
- generated_code_examples/javascript/classification/xgboost.js
- m2cgen/interpreters/javascript/interpreter.py
- m2cgen/interpreters/javascript/linear_algebra.js
- m2cgen/interpreters/javascript/sigmoid.js
- m2cgen/interpreters/javascript/softmax.js
- tests/interpreters/test_javascript.py
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#browser_compatibility
> Use `var` instead of `let` in JS generator for better backward compatibility

- tests/interpreters/test_dart.py
- tests/interpreters/test_f_sharp.py
- tests/interpreters/test_java.py
- tests/interpreters/test_python.py
- tests/interpreters/test_r.py
> Add tests for depth threshold mixin with reused expr

- tests/assemblers/test_linear.py
- tests/assemblers/test_meta.py
- tests/assemblers/test_svm.py
> Add test for norm in SVM cosine kernel

- m2cgen/assemblers/boosting.py
- m2cgen/assemblers/fallback_expressions.py
- m2cgen/assemblers/tree.py
- m2cgen/assemblers/utils.py
- tests/assemblers/test_lightgbm.py
> Add test for unknown objectives in LightGBM

- .ci/test.sh
- .github/workflows/main.yml
> Feb 1, 2022, and onward: The Bash Uploader will be fully sunset and will no longer function.
https://docs.codecov.com/docs/about-the-codecov-bash-uploader
> Use new Codecov uploader

- README.md
> Stop using Boston dataset in examples

- .ci/test.sh
Refer to https://github.com/BayesWitnesses/m2cgen/pull/447#discussion_r796158630.
> Skip flaky Elixir test

- Dockerfile
Taken from here https://github.com/joblib/joblib/blob/4dafaff788a3b5402acfed091558b4c511982959/joblib/_parallel_backends.py#L40-L44
> Set `NUMBA_NUM_THREADS` env variable to 2 in the Docker file
