- m2cgen/assemblers/tree.py
- tests/e2e/executors/base.py
- tests/e2e/executors/java.py
- tests/e2e/executors/python.py
- tests/e2e/test_e2e.py
- tests/utils.py
1. Use float32 for all thresholds in TreeModelAssembler
2. Add printing of commands(Java) and files(python) in Executors. It will only be seen in failed tests.
> Fix e2e tests: use float32 for all thresholds in TreeModelAssembler

- m2cgen/assemblers/ensemble.py
- m2cgen/assemblers/linear.py
- m2cgen/assemblers/tree.py
- m2cgen/ast.py
- m2cgen/interpreters/java/interpreter.py
- tests/assemblers/test_linear.py
- tests/assemblers/test_tree.py
- tests/e2e/test_e2e.py
- tests/interpreters/test_java.py
1. Move is_multi_output to all Expressions
2. Remove MainExpr/is_multi_output from assemblers
3. Remove MainExpr from tests
> Move is_multi_output to all Expressions; remove MainExpr from ensembles

- m2cgen/assemblers/linear.py
- m2cgen/assemblers/utils.py
- tests/e2e/conftest.py
- tests/e2e/test_e2e.py
1. Add python/java markers to parameters so that now we can invoke only subset of tests:
`pytest tests/e2e/test_e2e.py -m python`
2. Add `--fast` flag for e2e tests which will limit each combination of model/language to run on a single row from dataset. Useful for development
> Improvements for e2e tests

- m2cgen/assemblers/boosting.py
- tests/assemblers/test_xgboost.py
Currently the XGBoostModelAssembler ignores ntree_limit in the XGBoost model. This differs with the sklearn implementation of XGBoost models. This fix respects the ntree_limit (if exists) when building the transpiled model.
> Add ntree-limit fix for XGBoostModelAssembler

- m2cgen/assemblers/boosting.py
- tests/assemblers/test_xgboost.py
Now it's not fail if XGBoost model were saved by save without feature names
> Fixed missing feature names for XGBoost

- .travis.yml
- .travis/setup.sh
- .travis/test.sh
Refer to https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-32415710.
Seems that without this change Travis reflects only status of the last command in script in the job status.
See the current `master` build as an example of incorrectly reported status: https://travis-ci.org/BayesWitnesses/m2cgen/jobs/629771258?utm_medium=notification&utm_source=github_status.
> fix Travis to report failures

- tests/interpreters/test_r.py
To be consistent with test collection for Java, another interpreter inheriting `mixins.SubroutinesAsFunctionsMixin`
https://github.com/BayesWitnesses/m2cgen/blob/03abb92b312612af122187c36bff8987417ba069/tests/interpreters/test_java.py#L162-L179
> added test_subroutine for R

- m2cgen/assemblers/boosting.py
Apparently the `average_output` attribute is not available in model dumps from older LightGBM versions (tested with 2.2.2).
> Fix support of older LightGBM versions

- README.md
- m2cgen/assemblers/tree.py
- setup.py
`scikit-learn` and `scipy` are quite "heavy" dependencies and rather often have conflicts with certain versions of other ML libraries. Dropping them from a list of required packages for `m2cgen` installation will allow users to be freer in configuring their virtual environments.
Some more my thoughts about the need of removing excess dependencies can be found in https://github.com/BayesWitnesses/m2cgen/issues/108#issue-508121116.
We do not require installation of `LightGBM` or `XGBoost`, for instance, to generate a code from their models. So I don't see any reasons why we should do this for `scikit-learn`.
> remove scikit-learn and scipy from dependencies

- README.md
- m2cgen/cli.py
- m2cgen/exporters.py
- m2cgen/interpreters/c/interpreter.py
- m2cgen/interpreters/c_sharp/interpreter.py
- m2cgen/interpreters/go/interpreter.py
- m2cgen/interpreters/java/interpreter.py
- m2cgen/interpreters/javascript/interpreter.py
- m2cgen/interpreters/php/interpreter.py
- m2cgen/interpreters/powershell/interpreter.py
- m2cgen/interpreters/python/interpreter.py
- m2cgen/interpreters/r/interpreter.py
- m2cgen/interpreters/visual_basic/interpreter.py
- tests/test_cli.py
Hello everyone,
First of all, thanks a ton for putting this tool/library together -- especially in resource-stranded environments, it does have a potential to literally save lives!
One small problem I was fighting with while using it was the `score` function it uses in the generated modules. When they are used as drop-in replacements for trained models, using `score` is a bit strange, as the API generally provides function like `predict` or `predict_proba`. It would therefore be of great help to me if this name could be dynamically changed and I would not have to do so manually.
Please do let me know if something like this sounds like a sensible addition. I'd be happy to update the code so that it reflect your vision, so please feel free to just let me know whenever that may be the case. …
> add: Make function_name parametrized

- .travis.yml
- tests/e2e/test_e2e.py
Require that language marks should be at least "standard searchable" 3 symbols length. It allows to use them in different conditions in Travis scripts.
> made language marks long enough

- m2cgen/assemblers/boosting.py
- m2cgen/ast.py
- tests/e2e/test_e2e.py
- tests/test_ast.py
As it turns out the issue reported in https://github.com/BayesWitnesses/m2cgen/issues/168 is not unique to the "hist" tree construction algorithm. It seems that with "hist" method the likelihood of reprdocue is much higher due to relying on feature histograms. I was able to reproduce the same discrepancy with non-hist methods on a larger sample of test data.
The issue occurs due to a double precision error and reproduces every time when the feature value matches the split condition in one of the tree's nodes. 
Example: feature value = `0.671`, split condition = `0.671000004`. When we hit this condition in the generated code the outcome of `0.671 <  0.671000004` is "true" (or "yes" branch). While in XGBoost the same condition leads to the "no" branch.
After some investigation I noticed …
> Fix #168. Enforce float32 type for split condition values for GBT models created using XGBoost

- m2cgen/ast.py
- m2cgen/interpreters/interpreter.py
- m2cgen/interpreters/utils.py
This method (now function to not overcomplicate the code with handling of two decorators) is used very extensively. So the profit of caching it is obvious.
For example,
```
import sys
from sklearn.datasets import load_boston
import lightgbm as lgb
import m2cgen as m2c
X, y = load_boston(True)
est = lgb.LGBMRegressor(n_estimators=1000, random_state=42).fit(X, y)
sys.setrecursionlimit(int(1e5))
_ = m2c.export_to_python(est)
m2c.interpreters.utils._get_handler_name.cache_info()
```
```
CacheInfo(hits=97666, misses=5, maxsize=16, currsize=5)
```
> cache handler names

- .travis.yml
- .travis/setup.sh
- Dockerfile
- README.md
- m2cgen/__init__.py
- m2cgen/cli.py
- m2cgen/exporters.py
- m2cgen/interpreters/__init__.py
- m2cgen/interpreters/ruby/code_generator.py
- m2cgen/interpreters/ruby/interpreter.py
- m2cgen/interpreters/ruby/linear_algebra.rb
- tests/e2e/executors/__init__.py
- tests/e2e/executors/haskell.py
- tests/e2e/executors/php.py
- tests/e2e/executors/ruby.py
- tests/e2e/test_e2e.py
- tests/interpreters/test_ruby.py
Ruby is in top15 TIOBE latest rating: https://www.tiobe.com/tiobe-index/. 🙂 
I expect that adding Ruby support will be demanded not only in pure Ruby itself, but in **Ruby on Rails** web framework which is among popular frameworks: [1](https://medium.com/front-end-weekly/10-most-popular-web-frameworks-in-2020-167b9103e08a), [2](https://hotframeworks.com/).
> added Ruby code generator

- m2cgen/ast.py
- m2cgen/interpreters/interpreter.py
- tests/test_ast.py
Introduce helper `IdExpr` identity expression, which can be useful in case when you need to overwrite behavior (e.g. `to_reuse` flag) of passed expression.
Refer to https://github.com/BayesWitnesses/m2cgen/pull/199#discussion_r421635242.
> added IdExpr

- m2cgen/interpreters/c/interpreter.py
- m2cgen/interpreters/c_sharp/interpreter.py
- m2cgen/interpreters/code_generator.py
- m2cgen/interpreters/dart/interpreter.py
- m2cgen/interpreters/go/interpreter.py
- m2cgen/interpreters/haskell/interpreter.py
- m2cgen/interpreters/java/interpreter.py
- m2cgen/interpreters/javascript/interpreter.py
- m2cgen/interpreters/mixins.py
- m2cgen/interpreters/php/interpreter.py
- m2cgen/interpreters/powershell/interpreter.py
- m2cgen/interpreters/python/interpreter.py
- m2cgen/interpreters/r/interpreter.py
- m2cgen/interpreters/ruby/interpreter.py
- m2cgen/interpreters/visual_basic/interpreter.py
While changes in #207 are arguably giving significant improvement, the speedup achieved by these updates can be seen on transpiling medium-size models without any profiling tools.
During skimming the report from https://github.com/BayesWitnesses/m2cgen/pull/207#issuecomment-625898131, I noticed that `add_code_line()` takes a huge amount of time (also refer to #209 for another strings-related improvement).
Here is a simple bench.
```
import sys
from sklearn.datasets import load_boston
import lightgbm as lgb
import m2cgen as m2c
X, y = load_boston(True)
est = lgb.LGBMRegressor(n_estimators=1000, random_state=42).fit(X, y)
sys.setrecursionlimit(int(1e5))
%%timeit -n7 -r5
_ = m2c.export_to_python(est)
```
And the results are the following:
```
30.6 s ± 16.9 ms per loop (mean ± std. dev. of 5 …
```
> use string buffer to store generated code

- m2cgen/assemblers/boosting.py
`math` is faster for scalars than `numpy`. Refer to https://github.com/BayesWitnesses/m2cgen/issues/108#issue-508121116.
> use math.log for scalars

- .travis.yml
This PR eliminates duplicated jobs at CI and saves a lot of time. Now Travis is only triggered for
- `master` branch;
- all PRs to `master`.
One can just comment new added line in config file to test changes for any other branch before submitting a PR.
> run CI only for master branch and PRs

- README.md
We have dropped Travis CI support in #272.
> remove Travis badge

- tests/utils.py
```
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:70: FutureWarning: Pass return_X_y=True as keyword args. From version 0.25 passing these as positional arguments will result in an error FutureWarning)
```
> fix FutureWarning from scikit-learn

- Dockerfile
- m2cgen/assemblers/boosting.py
- tests/assemblers/test_lightgbm.py
- tests/e2e/executors/c.py
- tests/e2e/executors/c_sharp.py
- tests/e2e/executors/dart.py
- tests/e2e/executors/f_sharp.py
- tests/e2e/executors/go.py
- tests/e2e/executors/haskell.py
- tests/e2e/executors/java.py
- tests/e2e/executors/javascript.py
- tests/e2e/executors/php.py
- tests/e2e/executors/powershell.py
- tests/e2e/executors/r.py
- tests/e2e/executors/ruby.py
- tests/e2e/executors/visual_basic.py
- tests/e2e/test_e2e.py
- tests/utils.py
Sometimes exported LGBMRegressor model's prediction doesn't match predictions from the original model. This happens when model encounters values missing during training. More detailed discussion could be found here https://github.com/microsoft/LightGBM/issues/2921 
This is by no means a complete fix for the problem, it only addresses this part of the LightGBM behavior:
"for numerical features, if not missing is seen in training, the missing value will be converted to zero, and then check it with the threshold. So it is not always the left side."
Fix has also being tested on fairly big regression model with numerical features and it works as expected.
How to reproduce:
````
import numpy as np
import lightgbm as lgb
import m2cgen as m2c
from sklearn.datasets import load_diabetes
dataset = …
```
> Handle missing values replacement in LightGBM

- Dockerfile
I remember we had to move to Zulu in LightGBM project due to changed license agreement and limited support. As we are now using our Docker at CI services (and possibly will produce artifacts from it) I think we should do the same.
To be honest, I'm far away from legal aspects of software development, but I believe we should use only things that are totally free and have no pitfalls.
Echoing myself [from the past](https://github.com/microsoft/LightGBM/pull/2170#issue-278245842):
Azul Zulu 
- free to use,
- updated regularly.
I can say that Zulu implementation looks quite stable as there have been no issues with it for more than one year in the LightGBM repo (https://github.com/guolinke/lightgbm-ci-docker/pull/1).
Some refs:
https://azure.microsoft.com/en-us/blog/microsoft-and-azul-systems-b …
> migrate from OpenJDK to Zulu

- m2cgen/interpreters/dart/interpreter.py
- m2cgen/interpreters/dart/linear_algebra.dart
- tests/interpreters/test_dart.py
Release changes: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#2120---2021-03-03.
- Fix `Error: A value of type 'num' can't be returned from a function with return type 'double'.` for [`pow` function](https://api.dart.dev/stable/2.12.2/dart-math/pow.html). Also, I checked all other functions used in `m2cgen` https://github.com/BayesWitnesses/m2cgen/blob/6b0ede152ac35cdafe8c91b0e54144dfd09efc06/m2cgen/interpreters/dart/interpreter.py#L24-L31 and they all return `double` typed result by default.
- Fix `Error: Can't use the default List constructor.` Refer to https://api.dart.dev/stable/2.12.2/dart-core/List/List.html
> `@Deprecated("Use a list literal, [], or the List.filled constructor instead")`
> support latest Dart 2.12 version

- .github/workflows/main.yml
Simply workflow code greatly by deduplicating code of `API` and `E2E` jobs.
Refer to https://github.com/BayesWitnesses/m2cgen/pull/272#issuecomment-663103345 for the initial thoughts why languages were factored out from job names.
> Rework GitHub workflow to specify only one job as required

- setup.cfg
Increase max allowed code line length from old-fashioned inconvenient 80 chars to more comfortable 120 chars.
> Increase max line length limit

- .github/workflows/main.yml
Right now `r_lang or dart` job takes about 3 hours. Moving `dart` to `powershell` (<1h for new combined job) should decrease the overall test time.
> Reorganize languages in CI jobs

- m2cgen/assemblers/boosting.py
In most recent XGBoost versions feature indices can has string type in json model representation.
> Improve feature references in split condition for most recent XGBoost versions

- Dockerfile
- requirements-test.txt
Supersede broken #357.
Support for Python 3.6 was dropped in Numpy 1.20 release.
> The Python versions supported for this release are 3.7-3.9, support for Python 3.6 has been dropped.
https://github.com/numpy/numpy/blob/main/doc/source/release/1.20.0-notes.rst#numpy-1200-release-notes
> Bump numpy from 1.19.2 to 1.20.2

- requirements-test.txt
Current master cannot be installed with Python 3.9.
https://github.com/scikit-learn-contrib/lightning/pull/154
Needed by #371.
> Bump lightning version

- m2cgen/interpreters/c/interpreter.py
- tests/interpreters/test_c.py
Partly reverts #399 for languages in which order of function definition matters.
> Fix C lang interpreter

- tests/conftest.py
- tests/e2e/test_cli.py
- tests/test_cli.py
Fixtures with `scope="module"` allow to save some time by executing their code once per test module instead of running that code in each test function as previously.
> Move resource allocations for CLI tests in pytest fixtures

- .codecov.yml
Content of these files is already used in Python interpreter tests, e.g. here
https://github.com/BayesWitnesses/m2cgen/blob/975d8176953a07c826572350d9fdbfb6c6960ca5/tests/interpreters/test_python.py#L446-L461
Increase code coverage.
> Ignore Python files with math functions in calculating code coverage

- m2cgen/assemblers/linear.py
- tests/assemblers/test_linear.py
Increase code coverage.
Also, convert `@pytest.mark.xfail` into `pytest.raises` because `xfail` is mostly for
> known bugs or missing features.
https://docs.pytest.org/en/latest/reference/reference.html#pytest-xfail
`pytest.raises` makes tests more precise. Also, error message cannot be specified in `xfail`.
> Add test for unknown model in statsmodels

- README.md
Starting from Python 3.5 `RecursionError` is raised instead of plain `RuntimeError`.
> New in version 3.5: Previously, a plain `RuntimeError` was raised.
https://docs.python.org/3/library/exceptions.html#RecursionError
https://docs.python.org/3/library/sys.html#sys.setrecursionlimit
> Update error type in FAQ about recursion error

- .github/workflows/main.yml
- README.md
- requirements-test.txt
- setup.py
- tests/e2e/executors/powershell.py
- tests/e2e/test_cli.py
Python 3.6 reached its End of Life in December 2021 and there is no need to support it anymore.
https://devguide.python.org/devcycle/#security-branches
> Drop Python 3.6 support

- .ci/test.sh
- .github/workflows/main.yml
Use GitHub Actions to generate code examples for each commit and pack them into a downloadable artifact.
Artifact can be downloaded then from corresponding CI job page (can be found under the **Artifacts** heading after all jobs are finished).
> Generate artifact with code examples

- m2cgen/cli.py
- tests/test_cli.py
Hi! I faced the problem that some models that were dumped using joblib cannot be loaded using pickle in m2cgen i.e. DecisionTreeClassifier from scikit-learn. This leads to undefined behavior further down in the code.
Works file:
```
from pickle import dump
f = open("model.pkl","wb")
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
dump(clf, f) 
```
Won't work:
```
from joblib import dump
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
dump(clf, "model.pkl") 
```
Traceback looks like:
```
Traceback (most recent call last):
File "~/miniconda3/bin/m2cgen", line 8, in <module>
sys.exit(main())
File "~/miniconda3/lib/python3.9/site-packages/m2cgen/cli.py", line 137, in main
print(generate_code(args))
File "~/miniconda3/lib/python3.9/site-packages/m2cgen/cli.py", line …
```
> fix joblib model loading
